owner: n8n-io
repo: n8n-cloud-status

# Add your sites here
sites:
  - name: n8n.io
    url: https://www.n8n.io
    assignees:
      - BHesseldieck
  - name: n8n.cloud
    url: https://app.n8n.cloud/login
  - name: n8n.cloud - Backend Services
    url: $ADMINPANEL_BE_HEALTH
    icon: https://n8n.io/favicon.ico
  - name: n8n.cloud - Instance Cluster
    url: $CLUSTER_HEALTH
    icon: https://n8n.io/favicon.ico
  # - name: Broken Site
  #   url: https://thissitedoesnotexist.com
  # - name: Test for HEAD
  #   method: HEAD
  #   url: https://www.google.com
  # - name: Secret Site
  #   url: $SECRET_SITE
  # - name: TCP ping
  #   url: 1.1.1.1

assignees: # Users to assign downtime issues
  - BHesseldieck
  - ahsanv

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: status.n8n.cloud
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /n8n-cloud-status
  themeUrl: https://n8n-io.github.io/n8n-cloud-status/themes/n8n.css
  logoUrl: https://uploads-ssl.webflow.com/5fb23fba106ce3c8a0b50fdf/5fcfde2bb7d862dfe9f46aca_n8n-cloud-wordmark_beta_v2.svg
  favicon: https://n8n.io/favicon.ico
  name: Status
  introTitle: "**n8n.cloud** service monitoring."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: n8n.cloud
      href: https://n8n.cloud
    - title: n8n.io
      href: https://n8n.io
